version: "3.3"
services:

  video-loop-source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:latest
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - /tmp/video-loop-source-downloads:/tmp/video-loop-source-downloads
    environment:
      - LOCATION=https://merlin-assets-bucket-dev.s3.ap-south-1.amazonaws.com/mwc-sample-videos/traffic-video-youtube.mp4
      - DOWNLOAD_PATH=/tmp/video-loop-source-downloads
      - ZMQ_ENDPOINT=pub+connect:ipc:///tmp/zmq-sockets/input-video.ipc
      - SOURCE_ID=cctv-1
      - SYNC_OUTPUT=True
    entrypoint: /opt/savant/adapters/gst/sources/video_loop.sh

  module:
    build:
      context: .
      dockerfile: docker/Dockerfile.x86
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../../models/people_counting:/models
      - ../../downloads/people_counting:/downloads
      - .:/opt/savant/samples/people_counting
    command: samples/people_counting/module-${DETECTOR}.yml
    environment:
      - ZMQ_SRC_ENDPOINT=sub+bind:ipc:///tmp/zmq-sockets/input-video.ipc
      - ZMQ_SINK_ENDPOINT=pub+bind:ipc:///tmp/zmq-sockets/output-video.ipc
      - FPS_PERIOD=1000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  image-file-sink:
    image: ghcr.io/insight-platform/savant-adapters-py:latest
    restart: unless-stopped
    volumes:
      - ../../results/:/results/
      - zmq_sockets:/tmp/zmq-sockets
    environment:
      - ZMQ_ENDPOINT=sub+connect:ipc:///tmp/zmq-sockets/output-video.ipc
      - DIR_LOCATION=/results/%source_id-%source_filename
      - CHUNK_SIZE=10
    entrypoint: /opt/savant/adapters/python/sinks/image_files.py

  always-on-sink:
    image: ghcr.io/insight-platform/savant-adapters-deepstream:latest
    restart: unless-stopped
    ports:
      - "554:554" # RTSP
      - "1935:1935" # RTMP
      - "888:888" # HLS
      - "8889:8889" # WebRTC
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../assets/stub_imgs:/stub_imgs
    environment:
      - ZMQ_ENDPOINT=sub+connect:ipc:///tmp/zmq-sockets/output-video.ipc
      - SOURCE_ID=cctv-1
      - STUB_FILE_LOCATION=/stub_imgs/smpte100_1280x720.jpeg
      - DEV_MODE=True
    command: python -m adapters.ds.sinks.always_on_rtsp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  zmq_sockets:
